### ISSUE TITLE
deploy error File exists @ dir_s_mkdir

### ISSUE THREAD

**Issue by stanstrup** [rformassspectrometry/metaRbolomics-book#1]
Looks like there is a bug in dpl that makes deploy fail if there is no gh-pages branch: https://travis-ci.community/t/file-exists-dir-s-mkdir-ruby-exception-when-the-deploy-branch-doesnt-exist/1143

I have create an empty branch and is retesting.

**Comment by lgatto** [comment]
But you also build into a `public` directory that doesn't exists. Is it going to be created automatically? 

My default pipeline is to build in `docs` in the master branch (and set accordingly in the repo settings) which works like a charm.

**Comment by stanstrup** [comment]
Yes `public` is created by bookdown.
I wanted to avoid committing output files in the repo. I find this much cleaner and convenient. I don't have to wait to compile to push small changes.

Anyway. It seems the workaround works.
I wasn't aware that the travis deploy pages would push to the (gh-pages branch of the) repo but apparently that is how it works. And a bug prevented that if the branch wasn't already there.

So with this fix the book builds and everything seems to work perfectly. @sneumann
