### ISSUE TITLE
add IPA package to metaRbolomics book

### ISSUE THREAD

**Issue by mvinaixa** [rformassspectrometry/metaRbolomics-book#21]
Please consider adding Integrated Probabilistic Annotation (IPA) - A Bayesian annotation method for LC/MS data integrating biochemical relations, isotope patterns and adduct formation

Reference https://doi.org/10.1021/acs.analchem.9b02354
Available from https://github.com/francescodc87/IPA

**Comment by mvinaixa** [comment]
Please allow me googlesheet edit access

**Comment by stanstrup** [comment]
Did you click the button to request access?

**Comment by sneumann** [comment]
Ok, got it now (twice). Yours, Steffen

**Comment by mvinaixa** [comment]
done! 

Please mind this is just a  "just accepted manuscript".  No issue number o page number yet.  Thus, I have not included it in your references.bib file. Do it at your best convenience. Find bellow the BibTex entry just in case. 

@article{DelCarratore_2019,
annote = {doi: 10.1021/acs.analchem.9b02354},
author = {{Del Carratore}, Francesco and Schmidt, Kamila and Vinaixa, Maria and Hollywood, Katherine Anne and Greenland-Bews, Caitlin and Takano, Eriko and Rogers, Simon and Breitling, Rainer},
doi = {10.1021/acs.analchem.9b02354},
issn = {0003-2700},
journal = {Analytical Chemistry},
month = {sep},
publisher = {American Chemical Society},
title = {{Integrated Probabilistic Annotation (IPA): A Bayesian-based annotation method for metabolomic profiles integrating biochemical connections, isotope patterns and adduct relationships}},
url = {https://doi.org/10.1021/acs.analchem.9b02354},
year = {2019}
}

**Comment by stanstrup** [comment]
Thanks! Added reference. Book is updated.
