### ISSUE TITLE
Rendering broken due to chrome issues

### ISSUE THREAD

**Issue by stanstrup** [rformassspectrometry/metaRbolomics-book#30]
@nilshoffmann did some nice updates but the rendering has failed since.

It seems to be because the chrome package changed from chromium-l10n to chromium-browser.
I changed what apt-get installs but I am running into a myriad of issues. Before I spend more time on this perhaps someone that usually works with Linux knows what is going on? @sneumann 

First I got complaints about path to chrome, then it seems to need some `snap` to actually run chrome but I have no idea what that is supposed to do and cannot get it working.

**Comment by nilshoffmann** [comment]
@stanstrup Sorry for that. Will check if I can fix it!

**Comment by stanstrup** [comment]
I don't think it was your update that broke it but that the ubuntu used for the github workflow changed.
But would be very grateful if you can figure out how to get it back on track.

**Comment by nilshoffmann** [comment]
@stanstrup Could this be due to changes in Googles REST API? Just found this: https://github.com/tidyverse/googlesheets4
Seems like we are still using the older version in the script.

**Comment by stanstrup** [comment]
No, we never get that far. It fails on installing linux packages: https://github.com/rformassspectrometry/metaRbolomics-book/runs/1874033174?check_suite_focus=true

**Comment by nilshoffmann** [comment]
The following fixes the build using the latest rocker Docker image as a base (using Ubuntu 20.04), at least until I hit:

`! LaTeX Error: Option clash for package xcolor`

I tried to place this in a new file (pinChromium.sh)
`#!/bin/bash

cat <<EOF | sudo tee /etc/apt/sources.list.d/bionic-updates.list
deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe 
EOF

cat <<EOF | sudo tee /etc/apt/preferences.d/chromium-deb-bionic-updates
Package: chromium-browser chromium-browser-l10n chromium-codecs-ffmpeg-extra chromium-codecs-ffmpeg
Pin: release a=bionic-updates
Pin-Priority: 900
EOF
`
Then added the following two lines to the Dockerfile below the FROM ... line:
`
ADD pinChromium.sh /tmp

RUN /tmp/pinChromium.sh
`

and adapted the following line: 

`
ENV CHROMOTE_CHROME /usr/bin/chromium-browser
`

Then built the Docker image with 

`docker build .`

And adapting the travisScript.sh file to use the digest of the newly built container.

**Comment by nilshoffmann** [comment]
The travis build still complains about this:
`Package xcolor Warning: Incompatible color definition on input line 1816.`
GitHub actions is just complaining about deprecation in https://github.com/rformassspectrometry/metaRbolomics-book/runs/2167721661?check_suite_focus=true#step:6:834
