### ISSUE TITLE
Add MsCoreUtils, Spectra and the Backend classes/packages

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/metaRbolomics-book#31]
Add `Spectra` and `MsBackendMgf` to section 2.1 and `Spectra`, `MsCoreUtils`, `MsBackendMassbank` and `MsBackendHmdb` to section 2.2.

Unless you want only packages published in scientific journals to be added @stanstrup

**Comment by jorainer** [comment]
Had a look at the book, but could not find the tables anywhere. How can I add content to the tables?

**Comment by sneumann** [comment]
yes, there should be a link to a google doc somewhere. Yours, Steffen

**Comment by stanstrup** [comment]
merged
