### ISSUE TITLE
Formatting issues in HTML version

### ISSUE THREAD

**Issue by nilshoffmann** [rformassspectrometry/metaRbolomics-book#35]
Chapter 1, Sections 2.2, 2.3, 2.8, and Chapter 3 do not seem to use the same output format / section format than the "normal" sections.

**Comment by stanstrup** [comment]
I believe you are referring to the same as here? https://github.com/rformassspectrometry/metaRbolomics-book/issues/11

It should be solved by updating bookdown but was not when I tried last. should be re-tried.

**Comment by nilshoffmann** [comment]
Yes, sorry. Did not see that other issue.
